spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/monkeylog
    username: postgres
    password: mysecretpassword
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
  mvc:
    format:
      date-time: iso
