services:
  frontend-app:
    build:
      context: frontend-app
    ports:
      - 3000:3000
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  postgres-db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=monkeylog
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5433:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: {}