services:
  frontend:
    build:
      context: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - proxy-react
    depends_on:
      - backend
  backend:
    build:
      context: backend
      target: development
    networks:
      - proxy-spring
      - spring-postgresql
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=monkeylog
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - spring-postgresql
  proxy:
    build: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    networks:
      - proxy-spring
      - proxy-react

volumes:
  postgresql-data:

networks:
  proxy-react:
  proxy-spring:
  spring-postgresql:
