services:
  frontend-app:
    build:
      context: frontend-app
    ports:
      - 3000:3000
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true