spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml