run-name: Deploy to production
on:
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ vars.ENV_PRODUCTION }}" >> .env
          cat docker-compose.yml

      - uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: root@65.109.140.46
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deploy_path: ~/production-deployment
          stack_file_name: docker-compose.yml
          args: -p workoutlogbook up -d --build
